TARGET_CFLAGS=-mcpu=cortex-m0plus -mthumb

MODULES = \
    ../stm32/test \
    ../stm32/gpio \
    ../stm32/init \
    ../stm32/misc \
    ../stm32/nvic \
    ../stm32/prng \
    ../stm32/reset \
    ../stm32/semihosting \
    ../stm32/usart \
    ../stm32/vectors

include ../stm32/main.mk
