TARGET_CFLAGS=-mcpu=cortex-m3 -mthumb

MODULES += \
    ../stm32f103c8t6/gpio \
    ../stm32f103c8t6/init \
    ../stm32f103c8t6/nvic \
    ../stm32f103c8t6/usart \
    ../stm32f103c8t6/vectors

include ../stm32/main.mk
